-- Insert default user data
INSERT INTO `user` (email, first_name, last_name, password, pic_url, is_anonymous)
VALUES
('john@abc.com', 'john', 'doe', '123', 'https://example.com/john.jpg', 0),
('smith@abc.com', 'jane', 'smith', '456', 'https://example.com/jane.jpg', 1);

-- Insert default board data (this will trigger the insertion of default categories)
INSERT INTO `board` (user_id, title, show_name, show_like, show_comments, is_public)
VALUES
(1, 'Project Retro Board', 1, 1, 1, 1),
(2, 'Marketing Retro Board', 1, 1, 1, 1);

-- After inserting boards, the trigger will automatically add the following categories:
-- 'What went well', 'To improve', 'Actions', 'Others'

-- Insert sample cards for each category (these should match the category_id generated by the trigger)
-- First, you need to find the category_ids for each board. For example, for board_id = 1 (Project Retro Board),
-- 'What went well' might have category_id = 1, 'To improve' category_id = 2, etc.

-- Insert sample cards for board 1 (Project Retro Board)
INSERT INTO `card` (category_id, content, like_count, dislike_count)
VALUES
(1, 'Great communication among team members', 10, 1),
(2, 'Need to improve time management for tasks', 5, 2),
(3, 'Set clear deadlines for the next sprint', 15, 0),
(4, 'Organize team-building activities', 7, 1);

-- Insert sample cards for board 2 (Marketing Retro Board)
INSERT INTO `card` (category_id, content, like_count, dislike_count)
VALUES
(5, 'Successfully completed all milestones', 20, 0),
(6, 'Improve collaboration between departments', 8, 3),
(7, 'Plan next campaign strategies', 12, 2),
(8, 'Ensure team is aligned on goals', 9, 0);

-- Insert sample comments for each card
-- For each card_id, we associate a comment from a user. 

INSERT INTO `comment` (card_id, user_id, content)
VALUES
(1, 1, 'The communication has been amazing, loved how everyone contributed!'),
(2, 2, 'We should consider implementing time-tracking tools to improve this.'),
(3, 1, 'Clear deadlines will definitely help to streamline our workflow.'),
(4, 2, 'Team-building activities will definitely boost morale!'),
(5, 1, 'Impressive work on hitting all the targets this quarter.'),
(6, 2, 'Collaborating with other teams will definitely speed up our processes.'),
(7, 1, 'We need to start on new campaign ideas soon to stay ahead of the competition.'),
(8, 2, 'Aligning everyone on goals from the start will make execution smoother.');
